version: '3.19'

services:
  postgres:
    image: postgres
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - postgres:\Users\Micha\Desktop\Susurri_Database
  
volumes: 
  postgres:
    driver: \Users\Micha\Desktop\Susurri_Database